[2025-02-07T12:10:22.534+0000] {processor.py:186} INFO - Started process (PID=2196) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:10:22.535+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T12:10:22.539+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:10:22.539+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:10:22.551+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:10:22.549+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T12:10:22.552+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:10:22.552+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T12:10:22.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:10:22.565+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-02-07T12:21:59.355+0000] {processor.py:186} INFO - Started process (PID=5982) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:21:59.357+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T12:21:59.361+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:21:59.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:21:59.368+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:21:59.366+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T12:21:59.368+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:21:59.368+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T12:21:59.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:21:59.379+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-02-07T12:32:55.517+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:32:55.521+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T12:32:55.528+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:32:55.527+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:32:55.534+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:32:55.533+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T12:32:55.535+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:32:55.535+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T12:32:55.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:32:55.554+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2025-02-07T12:36:44.483+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:36:44.484+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T12:36:44.485+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:36:44.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:36:44.488+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:36:44.488+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T12:36:44.489+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:36:44.488+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T12:36:44.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:36:44.497+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-02-07T12:37:52.004+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:37:52.005+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T12:37:52.007+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:37:52.007+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:37:52.012+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:37:52.011+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T12:37:52.012+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:37:52.012+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T12:37:52.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:37:52.025+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-02-07T12:38:53.763+0000] {processor.py:186} INFO - Started process (PID=243) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:38:53.763+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T12:38:53.765+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:38:53.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:38:53.768+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:38:53.767+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T12:38:53.768+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:38:53.768+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T12:38:53.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:38:53.777+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-02-07T12:39:56.804+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:39:56.805+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T12:39:56.807+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:39:56.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:39:56.811+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:39:56.810+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T12:39:56.811+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:39:56.811+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T12:39:56.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:39:56.820+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-02-07T12:40:57.407+0000] {processor.py:186} INFO - Started process (PID=386) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:40:57.409+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T12:40:57.410+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:40:57.410+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:40:57.414+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:40:57.413+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T12:40:57.414+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:40:57.414+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T12:40:57.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:40:57.424+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-07T12:51:10.774+0000] {processor.py:186} INFO - Started process (PID=4107) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:51:10.776+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T12:51:10.781+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:51:10.781+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:51:10.787+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:51:10.786+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T12:51:10.788+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:51:10.788+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T12:51:10.788+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:51:10.800+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-07T12:59:09.212+0000] {processor.py:186} INFO - Started process (PID=7751) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:59:09.215+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T12:59:09.217+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:59:09.217+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:59:09.223+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:59:09.222+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T12:59:09.224+0000] {logging_mixin.py:190} INFO - [2025-02-07T12:59:09.224+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T12:59:09.224+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T12:59:09.240+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2025-02-07T13:08:25.850+0000] {processor.py:186} INFO - Started process (PID=1095) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:08:25.851+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T13:08:25.853+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:08:25.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:08:25.856+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:08:25.856+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T13:08:25.857+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:08:25.857+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T13:08:25.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:08:25.873+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-02-07T13:27:29.647+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:27:29.648+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T13:27:29.650+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:27:29.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:27:29.653+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:27:29.652+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T13:27:29.653+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:27:29.653+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T13:27:29.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:27:29.661+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-02-07T13:29:03.724+0000] {processor.py:186} INFO - Started process (PID=353) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:29:03.725+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T13:29:03.727+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:29:03.726+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:29:03.730+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:29:03.729+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T13:29:03.730+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:29:03.730+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T13:29:03.730+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:29:03.736+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-02-07T13:30:17.073+0000] {processor.py:186} INFO - Started process (PID=438) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:30:17.074+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T13:30:17.077+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:30:17.076+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:30:17.080+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:30:17.079+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T13:30:17.080+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:30:17.080+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T13:30:17.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:30:17.088+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-02-07T13:33:44.203+0000] {processor.py:186} INFO - Started process (PID=431) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:33:44.204+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T13:33:44.206+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:33:44.206+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:33:44.210+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:33:44.209+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T13:33:44.211+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:33:44.211+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T13:33:44.211+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:33:44.218+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-02-07T13:35:20.003+0000] {processor.py:186} INFO - Started process (PID=211) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:35:20.006+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T13:35:20.009+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:35:20.008+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:35:20.012+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:35:20.011+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T13:35:20.012+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:35:20.012+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T13:35:20.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:35:20.020+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-02-07T13:38:49.256+0000] {processor.py:186} INFO - Started process (PID=436) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:38:49.257+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T13:38:49.259+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:38:49.259+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:38:49.262+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:38:49.262+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T13:38:49.263+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:38:49.263+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T13:38:49.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:38:49.279+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-02-07T13:39:49.856+0000] {processor.py:186} INFO - Started process (PID=507) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:39:49.857+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T13:39:49.859+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:39:49.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:39:49.862+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:39:49.861+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T13:39:49.862+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:39:49.862+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T13:39:49.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:39:49.872+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-02-07T13:40:47.938+0000] {processor.py:186} INFO - Started process (PID=575) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:40:47.939+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T13:40:47.941+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:40:47.940+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:40:47.944+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:40:47.943+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T13:40:47.944+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:40:47.944+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T13:40:47.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:40:47.952+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-02-07T13:41:47.180+0000] {processor.py:186} INFO - Started process (PID=643) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:41:47.181+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T13:41:47.183+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:41:47.183+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:41:47.186+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:41:47.185+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T13:41:47.187+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:41:47.186+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T13:41:47.187+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:41:47.196+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-02-07T13:43:00.398+0000] {processor.py:186} INFO - Started process (PID=826) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:43:00.399+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T13:43:00.401+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:43:00.401+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:43:00.405+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:43:00.404+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T13:43:00.405+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:43:00.405+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T13:43:00.406+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:43:00.416+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-02-07T13:44:28.964+0000] {processor.py:186} INFO - Started process (PID=1018) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:44:28.965+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T13:44:28.969+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:44:28.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:44:28.973+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:44:28.973+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T13:44:28.976+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:44:28.976+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T13:44:28.976+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:44:28.989+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-02-07T13:46:04.876+0000] {processor.py:186} INFO - Started process (PID=1204) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:46:04.878+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T13:46:04.881+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:46:04.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:46:04.886+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:46:04.885+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T13:46:04.886+0000] {logging_mixin.py:190} INFO - [2025-02-07T13:46:04.886+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T13:46:04.886+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T13:46:04.900+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2025-02-07T14:05:23.350+0000] {processor.py:186} INFO - Started process (PID=1762) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T14:05:23.354+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T14:05:23.356+0000] {logging_mixin.py:190} INFO - [2025-02-07T14:05:23.355+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T14:05:23.360+0000] {logging_mixin.py:190} INFO - [2025-02-07T14:05:23.360+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T14:05:23.360+0000] {logging_mixin.py:190} INFO - [2025-02-07T14:05:23.360+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T14:05:23.361+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T14:05:23.374+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2025-02-07T14:06:27.217+0000] {processor.py:186} INFO - Started process (PID=1832) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T14:06:27.225+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T14:06:27.231+0000] {logging_mixin.py:190} INFO - [2025-02-07T14:06:27.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T14:06:27.238+0000] {logging_mixin.py:190} INFO - [2025-02-07T14:06:27.236+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T14:06:27.238+0000] {logging_mixin.py:190} INFO - [2025-02-07T14:06:27.238+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T14:06:27.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T14:06:27.262+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2025-02-07T14:07:48.038+0000] {processor.py:186} INFO - Started process (PID=2018) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T14:07:48.042+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-07T14:07:48.045+0000] {logging_mixin.py:190} INFO - [2025-02-07T14:07:48.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T14:07:48.052+0000] {logging_mixin.py:190} INFO - [2025-02-07T14:07:48.051+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-07T14:07:48.052+0000] {logging_mixin.py:190} INFO - [2025-02-07T14:07:48.052+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-07T14:07:48.053+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-07T14:07:48.070+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
